<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="canopusModel" nsURI="http://www.unipampa.lesse.org/canopusModel"
    nsPrefix="canopusModel">
  <eClassifiers xsi:type="ecore:EClass" name="Monitoring" eSuperTypes="#//Diagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="suts" eType="#//canopusPerformanceMonitoring/SUT"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loadGenerators" eType="#//canopusPerformanceMonitoring/LoadGenerator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitors" eType="#//canopusPerformanceMonitoring/Monitor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" eType="#//canopusPerformanceMonitoring/MetricModel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario" eSuperTypes="#//Diagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//canopusPerformanceScenario/UserProfile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workloads" upperBound="-1"
        eType="#//canopusPerformanceScenario/Workload" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1"
        eType="#//canopusPerformanceScenario/Association" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scripts" upperBound="-1"
        eType="#//canopusPerformanceScenario/Script" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scripting" eSuperTypes="#//Diagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial" lowerBound="1"
        eType="#//canopusPerformanceScripting/Initial" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="final" lowerBound="1" eType="#//canopusPerformanceScripting/Final"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" lowerBound="1"
        upperBound="-1" eType="#//canopusPerformanceScripting/Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="saveparameters" upperBound="-1"
        eType="#//canopusPerformanceScripting/SaveParameters" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatables" upperBound="-1"
        eType="#//canopusPerformanceScripting/DataTable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scripts" upperBound="-1"
        eType="#//canopusPerformanceScripting/ScriptingModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scripting" upperBound="-1"
        eType="#//Scripting" eOpposite="#//Scripting/scriptingeOpposite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scriptingeOpposite" upperBound="-1"
        eType="#//Scripting" eOpposite="#//Scripting/scripting"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Diagram" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectAuthor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="canopusPerformanceMonitoring" nsURI="http://www.unipampa.lesse.org/canopusPerformanceMonitoring"
      nsPrefix="canopusPerformanceMonitoring">
    <eClassifiers xsi:type="ecore:EClass" name="SUT">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hardware" eType="#//canopusPerformanceMonitoring/Hardware"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sut" eType="#//canopusPerformanceMonitoring/SUT"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="metricmodel" eType="#//canopusPerformanceMonitoring/MetricModel"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//canopusPerformanceMonitoring/SUTType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoadGenerator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sut" eType="#//canopusPerformanceMonitoring/SUT"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="metricmodel" eType="#//canopusPerformanceMonitoring/MetricModel"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hardware" eType="#//canopusPerformanceMonitoring/Hardware"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Monitor">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sut" eType="#//canopusPerformanceMonitoring/SUT"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hardware" eType="#//canopusPerformanceMonitoring/Hardware"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MetricModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="metricmodel" upperBound="-1"
          eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/MetricCollection"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SUTType">
      <eLiterals name="DESKTOPAPP"/>
      <eLiterals name="DATABASE" value="1"/>
      <eLiterals name="WEBAPP" value="2"/>
      <eLiterals name="WEBSERVICE" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Hardware">
      <eLiterals name="PHYSICA_MACHINE"/>
      <eLiterals name="VIRTUAL_MACHINE" value="1"/>
      <eLiterals name="CLOUD_SERVICE" value="2"/>
    </eClassifiers>
    <eSubpackages name="canopusPerformanceMetric" nsURI="http://www.unipampa.lesse.org/canopusPerformanceMetric"
        nsPrefix="canopusPerformanceMetric">
      <eClassifiers xsi:type="ecore:EClass" name="Memory" eSuperTypes="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Metric"/>
      <eClassifiers xsi:type="ecore:EClass" name="Disk" eSuperTypes="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Metric"/>
      <eClassifiers xsi:type="ecore:EClass" name="Metric" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MetricCollection">
        <eStructuralFeatures xsi:type="ecore:EReference" name="metric" lowerBound="1"
            upperBound="-1" eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Metric"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AssociationCounterCriteriaThreshold">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationCriteria"
            eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/ASSOCIATIONCRITERIA"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ASSOCIATIONCRITERIA">
        <eLiterals name="BETWEEN"/>
        <eLiterals name="GREATERTHANOREQUALTO" value="1"/>
        <eLiterals name="LESSTHAN" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AssociationMetricCounter"/>
      <eClassifiers xsi:type="ecore:EClass" name="Counter" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="enum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"
            transient="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DiskCounter" eSuperTypes="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Counter"/>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="canopusPerformanceScenario" nsURI="http://www.unipampa.lesse.org/canopusPerformanceScenario"
      nsPrefix="canopusPerformanceScenario">
    <eClassifiers xsi:type="ecore:EClass" name="UserProfile">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="script" upperBound="-1"
          eType="#//canopusPerformanceScenario/Script"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Workload">
      <eStructuralFeatures xsi:type="ecore:EReference" name="workload" lowerBound="1"
          upperBound="-1" eType="#//canopusPerformanceScenario/canopusPerformanceWorkload/WorkloadModel"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Script">
      <eStructuralFeatures xsi:type="ecore:EReference" name="scriptingmodel" eType="#//canopusPerformanceScripting/ScriptingModel"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Association">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="userprofile" eType="#//canopusPerformanceScenario/UserProfile"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="script" eType="#//canopusPerformanceScenario/Script"/>
    </eClassifiers>
    <eSubpackages name="canopusPerformanceWorkload" nsURI="http://www.unipampa.lesse.org/canopusPerformanceWorkload"
        nsPrefix="canopusPerformanceWorkload">
      <eClassifiers xsi:type="ecore:EClass" name="VirtualUsers">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtualUsers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TestDuration">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RampUpUsers">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtualUsers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RampDownUsers">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtualUsers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RampUpTimer">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RampDownTime">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WorkloadModel">
        <eStructuralFeatures xsi:type="ecore:EReference" name="testduration" eType="#//canopusPerformanceScenario/canopusPerformanceWorkload/TestDuration"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rampdownusers" eType="#//canopusPerformanceScenario/canopusPerformanceWorkload/RampDownUsers"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rampdowntime" eType="#//canopusPerformanceScenario/canopusPerformanceWorkload/RampDownTime"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rampuptimer" eType="#//canopusPerformanceScenario/canopusPerformanceWorkload/RampUpTimer"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rampupusers" eType="#//canopusPerformanceScenario/canopusPerformanceWorkload/RampUpUsers"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="virtualusers" eType="#//canopusPerformanceScenario/canopusPerformanceWorkload/VirtualUsers"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WorkloadGroup"/>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="canopusPerformanceScripting" nsURI="http://www.unipampa.lesse.org/canopusPerformanceScripting"
      nsPrefix="canopusPerformanceScripting">
    <eClassifiers xsi:type="ecore:EClass" name="Initial"/>
    <eClassifiers xsi:type="ecore:EClass" name="Final"/>
    <eClassifiers xsi:type="ecore:EClass" name="Activity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeAction" eType="#//canopusPerformanceScripting/TypeAction"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="loopInstances" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterhiddenobject"
          eType="#//canopusPerformanceScripting/ParameterHiddenObject" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transaction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" upperBound="-1"
          eType="#//canopusPerformanceScripting/Activity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ThinkTime">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SaveParameters">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterhiddenobject"
          eType="#//canopusPerformanceScripting/ParameterHiddenObject" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataTable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="delimeter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterhiddenobject"
          eType="#//canopusPerformanceScripting/ParameterHiddenObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attachedfile" eType="#//canopusPerformanceScripting/canopusPerformanceExternalFile/ExternalFile"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterHiddenObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeAction" eType="#//canopusPerformanceScripting/TypeAction"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="staticValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicvalues" eType="#//canopusPerformanceScripting/ColumnsHiddenObject"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TypeAction">
      <eLiterals name="BODY"/>
      <eLiterals name="BUTTON" value="1"/>
      <eLiterals name="CHECKBOX" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ColumnsHiddenObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="referendedParameter"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="selectnextrow" eType="#//canopusPerformanceScripting/SELECT_NEXT_ROW"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="updatedvalueon" eType="#//canopusPerformanceScripting/UPDATED_VALUE_ON"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="UPDATED_VALUE_ON">
      <eLiterals name="EACH_INTERACTION"/>
      <eLiterals name="EACH_OCCURENCE" value="1"/>
      <eLiterals name="ONCE" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SELECT_NEXT_ROW">
      <eLiterals name="SEQUENTIAL"/>
      <eLiterals name="RANDOM" value="1"/>
      <eLiterals name="UNIQUE" value="2"/>
      <eLiterals name="SAME_AS_OTHER_PARAM" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ScriptingModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
          upperBound="-1" eType="#//canopusPerformanceScripting/Activity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="saveparameters" upperBound="-1"
          eType="#//canopusPerformanceScripting/SaveParameters" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="datatable" upperBound="-1"
          eType="#//canopusPerformanceScripting/DataTable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="final" lowerBound="1"
          eType="#//canopusPerformanceScripting/Final" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initial" lowerBound="1"
          eType="#//canopusPerformanceScripting/Initial" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thinktime" upperBound="-1"
          eType="#//canopusPerformanceScripting/ThinkTime" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="porcentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
          upperBound="-1" eType="#//canopusPerformanceScripting/Activity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thinktime" upperBound="-1"
          eType="#//canopusPerformanceScripting/ThinkTime"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transaction"/>
    <eSubpackages name="canopusPerformanceExternalFile" nsURI="http://www.unipampa.lesse.org/canopusPerfoamnceExternalFile"
        nsPrefix="canopusPerformanceExternalFile">
      <eClassifiers xsi:type="ecore:EClass" name="ExternalFile">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
