<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="canopusModel" nsURI="http://www.unipampa.lesse.org/canopusModel"
    nsPrefix="canopusModel">
  <eClassifiers xsi:type="ecore:EClass" name="Monitoring" eSuperTypes="#//Diagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="suts" eType="#//canopusPerformanceMonitoring/SUT"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loadGenerators" eType="#//canopusPerformanceMonitoring/LoadGenerator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitors" eType="#//canopusPerformanceMonitoring/Monitor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" eType="#//canopusPerformanceMonitoring/MetricModel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario" eSuperTypes="#//Diagram"/>
  <eClassifiers xsi:type="ecore:EClass" name="Scripting" eSuperTypes="#//Diagram"/>
  <eClassifiers xsi:type="ecore:EClass" name="Diagram" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="canopusPerformanceMonitoring" nsURI="http://www.unipampa.lesse.org/canopusPerformanceMonitoring"
      nsPrefix="canopusPerformanceMonitoring">
    <eClassifiers xsi:type="ecore:EClass" name="SUT">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hardware" eType="#//canopusPerformanceMonitoring/Hardware"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sut" eType="#//canopusPerformanceMonitoring/SUT"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="metricmodel" eType="#//canopusPerformanceMonitoring/MetricModel"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//canopusPerformanceMonitoring/SUTType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Hardware">
      <eLiterals name=" Physical Machine (PM)"/>
      <eLiterals name="Virtual Machine (VM)" value="1"/>
      <eLiterals name="Cloud Service (CS)" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoadGenerator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sut" eType="#//canopusPerformanceMonitoring/SUT"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="metricmodel" eType="#//canopusPerformanceMonitoring/MetricModel"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hardware" eType="#//canopusPerformanceMonitoring/Hardware"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Monitor">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sut" eType="#//canopusPerformanceMonitoring/SUT"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hardware" eType="#//canopusPerformanceMonitoring/Hardware"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MetricModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="metricmodel" upperBound="-1"
          eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/MetricCollection"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SUTType">
      <eLiterals name="DesktopApp"/>
      <eLiterals name=" Database" value="1"/>
      <eLiterals name="WebApp" value="2"/>
      <eLiterals name="WebService" value="3"/>
    </eClassifiers>
    <eSubpackages name="canopusPerformanceMetric" nsURI="http://www.unipampa.lesse.org/canopusPerformanceMetric"
        nsPrefix="canopusPerformanceMetric">
      <eClassifiers xsi:type="ecore:EClass" name="Memory" eSuperTypes="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Metric"/>
      <eClassifiers xsi:type="ecore:EClass" name="Disk" eSuperTypes="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Metric"/>
      <eClassifiers xsi:type="ecore:EClass" name="Metric">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MetricCollection">
        <eStructuralFeatures xsi:type="ecore:EReference" name="metric" lowerBound="1"
            upperBound="-1" eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Metric"
            containment="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="canopusPerformanceScenario" nsURI="http://www.unipampa.lesse.org/canopusPerformanceScenario"
      nsPrefix="canopusPerformanceScenario">
    <eSubpackages name="canopusPerformanceWorkload" nsURI="http://www.unipampa.lesse.org/canopusPerformanceWorkload"
        nsPrefix="canopusPerformanceWorkload"/>
  </eSubpackages>
  <eSubpackages name="canopusPerformanceScripting" nsURI="http://www.unipampa.lesse.org/canopusPerformanceScripting"
      nsPrefix="canopusPerformanceScripting">
    <eSubpackages name="canopusPerformanceExternalFile" nsURI="http://www.unipampa.lesse.org/canopusPerfoamnceExternalFile"
        nsPrefix="canopusPerformanceExternalFile"/>
  </eSubpackages>
</ecore:EPackage>
