<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="canopus" nsURI="http://www.unipampa.lesse.org/canopus" nsPrefix="canopus">
  <eClassifiers xsi:type="ecore:EClass" name="Monitoring" eSuperTypes="#//Diagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="suts" upperBound="-1" eType="#//canopusPerformanceMonitoring/SUT"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loadGenerators" eType="#//canopusPerformanceMonitoring/LoadGenerator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitors" eType="#//canopusPerformanceMonitoring/Monitor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metricModel" upperBound="-1"
        eType="#//canopusPerformanceMonitoring/MetricModel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario" eSuperTypes="#//Diagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//canopusPerformanceScenario/UserProfile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workloads" upperBound="-1"
        eType="#//canopusPerformanceScenario/Workload" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1"
        eType="#//canopusPerformanceScenario/Association" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scripts" upperBound="-1"
        eType="#//canopusPerformanceScenario/Script" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scripting" eSuperTypes="#//Diagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial" lowerBound="1"
        eType="#//canopusPerformanceScripting/Initial" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="final" lowerBound="1" eType="#//canopusPerformanceScripting/Final"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" lowerBound="1"
        upperBound="-1" eType="#//canopusPerformanceScripting/Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="saveparameters" upperBound="-1"
        eType="#//canopusPerformanceScripting/SaveParameters" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatables" upperBound="-1"
        eType="#//canopusPerformanceScripting/DataTable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thinkTime" upperBound="-1"
        eType="#//canopusPerformanceScripting/ThinkTime" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scripting" upperBound="-1"
        eType="#//Scripting" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Diagram" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectAuthor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="canopusPerformanceMonitoring" nsURI="http://www.unipampa.lesse.org/canopusPerformanceMonitoring"
      nsPrefix="canopusPerformanceMonitoring">
    <eClassifiers xsi:type="ecore:EClass" name="SUT">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hardware" eType="#//canopusPerformanceMonitoring/HARDWARE"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sut" upperBound="-1"
          eType="#//canopusPerformanceMonitoring/SUT"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="metricmodel" eType="#//canopusPerformanceMonitoring/MetricModel"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//canopusPerformanceMonitoring/SUT_TYPE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoadGenerator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMonitor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sut" upperBound="-1"
          eType="#//canopusPerformanceMonitoring/SUT"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="metricmodel" eType="#//canopusPerformanceMonitoring/MetricModel"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hardware" eType="#//canopusPerformanceMonitoring/HARDWARE"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="monitor" eType="#//canopusPerformanceMonitoring/Monitor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Monitor">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sut" upperBound="-1"
          eType="#//canopusPerformanceMonitoring/SUT"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hardware" eType="#//canopusPerformanceMonitoring/HARDWARE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SUT_TYPE">
      <eLiterals name="DESKTOPAPP" literal="Desktop App"/>
      <eLiterals name="DATABASE" value="1" literal="Database"/>
      <eLiterals name="WEBAPP" value="2" literal="Web App"/>
      <eLiterals name="WEBSERVICE" value="3" literal="Web Service"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="HARDWARE">
      <eLiterals name="PHYSICAL_MACHINE" literal="Physical Machine (PM)"/>
      <eLiterals name="VIRTUAL_MACHINE" value="1" literal="Virtual Machine(VM)"/>
      <eLiterals name="CLOUD_SERVICE" value="2" literal="Cloud Service(CS)"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MetricModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="memory" eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Memory"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transaction" eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Transaction"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="disk" eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Disk"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="criteria" upperBound="-1"
          eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Criteria"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="threshold" upperBound="-1"
          eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Threshold"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="associationcountercriteriathreshold"
          upperBound="-1" eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/AssociationCounterCriteriaThreshold"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diskCounter" eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Disk_IO_Counter"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transactionCounter" eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/TransactionCounter"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="memoryCounter" eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/MemoryCounter"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="metric" upperBound="-1"
          eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Metric"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="counter" upperBound="-1"
          eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Counter"
          containment="true"/>
    </eClassifiers>
    <eSubpackages name="canopusPerformanceMetric" nsURI="http://www.unipampa.lesse.org/canopusPerformanceMetric"
        nsPrefix="canopusPerformanceMetric">
      <eClassifiers xsi:type="ecore:EClass" name="Memory" eSuperTypes="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Metric">
        <eStructuralFeatures xsi:type="ecore:EReference" name="memoryCounter" eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/MemoryCounter"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Disk" eSuperTypes="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Metric">
        <eStructuralFeatures xsi:type="ecore:EReference" name="disk_io_counter" eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Disk_IO_Counter"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Metric" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AssociationCounterCriteriaThreshold">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationCriteria"
            eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/ASSOCIATION_CRITERIA"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="threshold" eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Threshold"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="criteria" upperBound="-1"
            eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Criteria"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ASSOCIATION_CRITERIA">
        <eLiterals name="BETWEEN"/>
        <eLiterals name="GREATER_THAN_OR_EQUAL_TO" value="1" literal="GREATER THAN OR EQUAL TO"/>
        <eLiterals name="LESS_THAN" value="2" literal="LESS THAN"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Counter" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="associationcountercriteriathreshold"
            upperBound="-1" eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/AssociationCounterCriteriaThreshold"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Disk_IO_Counter" eSuperTypes="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Counter">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="counterDisk" upperBound="-1"
            eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/COUNTER_DISK"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Criteria">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Threshold">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="COUNTER_DISK">
        <eLiterals name="AVG_DISK_SECS_TRANSFER_COUNTER" literal="AVG DISK SECS TRANSFER COUNTER"/>
        <eLiterals name="PERCENTAGE_IDLE_TIME_COUNTER" value="1" literal="PERCENTAGE IDLE TIME COUNTER"/>
        <eLiterals name="DISK_TRANSFERS_SEC_COUNTER" value="2" literal="DISK TRANSFERS SEC COUNTER"/>
        <eLiterals name="AVG_DISK_QUEUE_LENGTH_COUNTER" value="3" literal="AVG DISK QUEUE LENGTH COUNTER"/>
        <eLiterals name="SPLIT_IO_SEC_COUNTER" value="4" literal="SPLIT IO SEC COUNTER"/>
        <eLiterals name="FREE_MEGABYTES_COUNTER" value="5" literal="FREE MEGABYTES COUNTER"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MemoryCounter" eSuperTypes="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Counter">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="counterMemory" upperBound="-1"
            eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/COUNTER_MEMORY"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="COUNTER_MEMORY">
        <eLiterals name="AVALIABLE_MBYTES_COUNTER" literal="AVALIABLE MBYTES COUNTER"/>
        <eLiterals name="PAGES_SEC_COUNTER" value="1" literal="PAGES SEC COUNTER"/>
        <eLiterals name="PAGE_READS_SEC_COUNTER" value="2" literal="PAGE READS SEC COUNTER"/>
        <eLiterals name="WORKING_SET_COUNTER" value="3" literal="WORKING SET COUNTER"/>
        <eLiterals name="POOL_NONPAGE_BYTES_COUNTER" value="4" literal="POOL NONPAGE BYTES COUNTER"/>
        <eLiterals name="PAGED_POOL_BYTES_COUNTER" value="5" literal="PAGED POOL BYTES COUNTER"/>
        <eLiterals name="PAGED_POOL_FAILURES_COUNTER" value="6" literal="PAGED POOL FAILURES COUNTER"/>
        <eLiterals name="CACHE_BYTES_COUNTER" value="7" literal="CACHE BYTES COUNTER"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Transaction" eSuperTypes="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Metric">
        <eStructuralFeatures xsi:type="ecore:EReference" name="transactionCounter"
            eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/TransactionCounter"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TransactionCounter" eSuperTypes="#//canopusPerformanceMonitoring/canopusPerformanceMetric/Counter">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="counterTransaction"
            upperBound="-1" eType="#//canopusPerformanceMonitoring/canopusPerformanceMetric/COUNTER_TRANSACTION"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="COUNTER_TRANSACTION">
        <eLiterals name="TRANSACTION_RESPONSE_TIME" literal="TRANSACTION RESPONSE TIME"/>
        <eLiterals name="TRANSACTION_PER_SECOND_TPS" value="1" literal="TRANSACTION PER SECOND (TPS)"/>
        <eLiterals name="TRANSACTION_SUCCESS_RATE" value="2" literal="TRANSACTION SUCCESS RATE"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="canopusPerformanceScenario" nsURI="http://www.unipampa.lesse.org/canopusPerformanceScenario"
      nsPrefix="canopusPerformanceScenario">
    <eClassifiers xsi:type="ecore:EClass" name="UserProfile">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="script" upperBound="-1"
          eType="#//canopusPerformanceScenario/Script"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Workload">
      <eStructuralFeatures xsi:type="ecore:EReference" name="workload" lowerBound="1"
          upperBound="-1" eType="#//canopusPerformanceScenario/canopusPerformanceWorkload/WorkloadModel"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Script">
      <eStructuralFeatures xsi:type="ecore:EReference" name="scriptingmodel" eType="#//canopusPerformanceScripting/ScriptingModel"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Association">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="userprofile" eType="#//canopusPerformanceScenario/UserProfile"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="script" eType="#//canopusPerformanceScenario/Script"/>
    </eClassifiers>
    <eSubpackages name="canopusPerformanceWorkload" nsURI="http://www.unipampa.lesse.org/canopusPerformanceWorkload"
        nsPrefix="canopusPerformanceWorkload">
      <eClassifiers xsi:type="ecore:EClass" name="VirtualUsers">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtualUsers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TestDuration">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RampUpUsers">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtualUsers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RampDownUsers">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtualUsers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RampUpTimer">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RampDownTime">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WorkloadModel">
        <eStructuralFeatures xsi:type="ecore:EReference" name="testduration" eType="#//canopusPerformanceScenario/canopusPerformanceWorkload/TestDuration"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rampdownusers" eType="#//canopusPerformanceScenario/canopusPerformanceWorkload/RampDownUsers"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rampdowntime" eType="#//canopusPerformanceScenario/canopusPerformanceWorkload/RampDownTime"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rampuptimer" eType="#//canopusPerformanceScenario/canopusPerformanceWorkload/RampUpTimer"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rampupusers" eType="#//canopusPerformanceScenario/canopusPerformanceWorkload/RampUpUsers"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="virtualusers" eType="#//canopusPerformanceScenario/canopusPerformanceWorkload/VirtualUsers"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="canopusPerformanceScripting" nsURI="http://www.unipampa.lesse.org/canopusPerformanceScripting"
      nsPrefix="canopusPerformanceScripting">
    <eClassifiers xsi:type="ecore:EClass" name="Initial">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
          eType="#//canopusPerformanceScripting/Activity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Final">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeAction" eType="#//canopusPerformanceScripting/TYPEACTION"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="loopInstances" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterhiddenobject"
          eType="#//canopusPerformanceScripting/ParameterHiddenObject" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transaction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" upperBound="-1"
          eType="#//canopusPerformanceScripting/Activity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scriptingmodel" eType="#//canopusPerformanceScripting/ScriptingModel"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="final" eType="#//canopusPerformanceScripting/Final"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thinktime" eType="#//canopusPerformanceScripting/ThinkTime"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ThinkTime">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//canopusPerformanceScripting/Activity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SaveParameters">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterhiddenobject"
          eType="#//canopusPerformanceScripting/ParameterHiddenObject" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataTable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="delimeter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterhiddenobject"
          eType="#//canopusPerformanceScripting/ParameterHiddenObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attachedfile" eType="#//canopusPerformanceScripting/canopusPerformanceExternalFile/ExternalFile"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//canopusPerformanceScripting/Activity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterHiddenObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeAction" eType="#//canopusPerformanceScripting/TYPEACTION"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="staticValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicvalues" eType="#//canopusPerformanceScripting/ColumnsHiddenObject"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TYPEACTION">
      <eLiterals name="BODY"/>
      <eLiterals name="BUTTON" value="1"/>
      <eLiterals name="CHECKBOX" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ColumnsHiddenObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="referendedParameter"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="selectnextrow" eType="#//canopusPerformanceScripting/SELECT_NEXT_ROW"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="updatedvalueon" eType="#//canopusPerformanceScripting/UPDATED_VALUE_ON"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="UPDATED_VALUE_ON">
      <eLiterals name="EACH_INTERACTION"/>
      <eLiterals name="EACH_OCCURENCE" value="1"/>
      <eLiterals name="ONCE" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SELECT_NEXT_ROW">
      <eLiterals name="SEQUENTIAL"/>
      <eLiterals name="RANDOM" value="1"/>
      <eLiterals name="UNIQUE" value="2"/>
      <eLiterals name="SAME_AS_OTHER_PARAM" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ScriptingModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
          upperBound="-1" eType="#//canopusPerformanceScripting/Activity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="saveparameters" upperBound="-1"
          eType="#//canopusPerformanceScripting/SaveParameters" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="datatable" upperBound="-1"
          eType="#//canopusPerformanceScripting/DataTable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="final" lowerBound="1"
          eType="#//canopusPerformanceScripting/Final" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initial" lowerBound="1"
          eType="#//canopusPerformanceScripting/Initial" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thinktime" upperBound="-1"
          eType="#//canopusPerformanceScripting/ThinkTime" containment="true"/>
    </eClassifiers>
    <eSubpackages name="canopusPerformanceExternalFile" nsURI="http://www.unipampa.lesse.org/canopusPerfoamnceExternalFile"
        nsPrefix="canopusPerformanceExternalFile">
      <eClassifiers xsi:type="ecore:EClass" name="ExternalFile">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
